name: map_mvp_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  image: ^3.0.2
  lottie: ^3.3.0
  file_picker: ^8.1.4
  flutter_svg: ^2.0.16
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  freezed_annotation: ^2.4.4
  dio: ^5.0.0
  logger: ^2.4.0
  carousel_slider: ^5.0.0
  mapbox_maps_flutter: ^2.5.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  string_scanner: ^1.2.0
  cupertino_icons: ^1.0.8
  uuid: 4.5.1

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/animations/lottie/
    - assets/earth_snapshot/